---

- hosts: all
  become: true
  tasks:

  - name: update repository index and install httpd package
    package:
      name: httpd
      state: present
      update_cache: true

  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "Rocky"
