---

- hosts: all
  become: true
  tasks:

  - name: update repository index and install apache and php package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: true

  - name: start and enable apache service
    service:
      name: "{{ apache_package }}"
      state: started
      enabled: true
