---

- hosts: all
  become: true
  tasks:

  - name: update repository index and remove apache and php package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent 
      update_cache: true
